# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 847)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cacheL1Proc0Chip0 = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.cacheL1Proc0Chip0.sizePolicy().hasHeightForWidth())
        self.cacheL1Proc0Chip0.setSizePolicy(sizePolicy)
        self.cacheL1Proc0Chip0.setMinimumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc0Chip0.setMaximumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc0Chip0.setBaseSize(QtCore.QSize(250, 95))
        self.cacheL1Proc0Chip0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc0Chip0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc0Chip0.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cacheL1Proc0Chip0.setAutoScroll(True)
        self.cacheL1Proc0Chip0.setObjectName("cacheL1Proc0Chip0")
        self.cacheL1Proc0Chip0.setColumnCount(6)
        self.cacheL1Proc0Chip0.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip0.setItem(1, 5, item)
        self.cacheL1Proc0Chip0.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout.addWidget(self.cacheL1Proc0Chip0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cacheL1Proc1Chip0 = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.cacheL1Proc1Chip0.sizePolicy().hasHeightForWidth())
        self.cacheL1Proc1Chip0.setSizePolicy(sizePolicy)
        self.cacheL1Proc1Chip0.setMinimumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc1Chip0.setMaximumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc1Chip0.setBaseSize(QtCore.QSize(250, 95))
        self.cacheL1Proc1Chip0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc1Chip0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc1Chip0.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cacheL1Proc1Chip0.setAutoScroll(True)
        self.cacheL1Proc1Chip0.setObjectName("cacheL1Proc1Chip0")
        self.cacheL1Proc1Chip0.setColumnCount(6)
        self.cacheL1Proc1Chip0.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip0.setItem(1, 5, item)
        self.cacheL1Proc1Chip0.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout.addWidget(self.cacheL1Proc1Chip0)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.cacheL2Chip0 = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacheL2Chip0.sizePolicy().hasHeightForWidth())
        self.cacheL2Chip0.setSizePolicy(sizePolicy)
        self.cacheL2Chip0.setMinimumSize(QtCore.QSize(322, 150))
        self.cacheL2Chip0.setMaximumSize(QtCore.QSize(322, 150))
        self.cacheL2Chip0.setBaseSize(QtCore.QSize(800, 300))
        self.cacheL2Chip0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL2Chip0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL2Chip0.setObjectName("cacheL2Chip0")
        self.cacheL2Chip0.setColumnCount(6)
        self.cacheL2Chip0.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip0.setItem(1, 5, item)
        self.cacheL2Chip0.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout.addWidget(self.cacheL2Chip0)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.sharedMemory = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sharedMemory.sizePolicy().hasHeightForWidth())
        self.sharedMemory.setSizePolicy(sizePolicy)
        self.sharedMemory.setMinimumSize(QtCore.QSize(227, 510))
        self.sharedMemory.setMaximumSize(QtCore.QSize(227, 16777215))
        self.sharedMemory.setBaseSize(QtCore.QSize(230, 0))
        self.sharedMemory.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sharedMemory.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sharedMemory.setObjectName("sharedMemory")
        self.sharedMemory.setColumnCount(2)
        self.sharedMemory.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sharedMemory.setItem(15, 1, item)
        self.verticalLayout_4.addWidget(self.sharedMemory)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.cacheL1Proc0Chip1 = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.cacheL1Proc0Chip1.sizePolicy().hasHeightForWidth())
        self.cacheL1Proc0Chip1.setSizePolicy(sizePolicy)
        self.cacheL1Proc0Chip1.setMinimumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc0Chip1.setMaximumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc0Chip1.setBaseSize(QtCore.QSize(250, 95))
        self.cacheL1Proc0Chip1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc0Chip1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc0Chip1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cacheL1Proc0Chip1.setAutoScroll(True)
        self.cacheL1Proc0Chip1.setObjectName("cacheL1Proc0Chip1")
        self.cacheL1Proc0Chip1.setColumnCount(6)
        self.cacheL1Proc0Chip1.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc0Chip1.setItem(1, 5, item)
        self.cacheL1Proc0Chip1.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout_3.addWidget(self.cacheL1Proc0Chip1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.cacheL1Proc1Chip1 = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.cacheL1Proc1Chip1.sizePolicy().hasHeightForWidth())
        self.cacheL1Proc1Chip1.setSizePolicy(sizePolicy)
        self.cacheL1Proc1Chip1.setMinimumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc1Chip1.setMaximumSize(QtCore.QSize(322, 93))
        self.cacheL1Proc1Chip1.setBaseSize(QtCore.QSize(250, 95))
        self.cacheL1Proc1Chip1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc1Chip1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL1Proc1Chip1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cacheL1Proc1Chip1.setAutoScroll(True)
        self.cacheL1Proc1Chip1.setObjectName("cacheL1Proc1Chip1")
        self.cacheL1Proc1Chip1.setColumnCount(6)
        self.cacheL1Proc1Chip1.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL1Proc1Chip1.setItem(1, 5, item)
        self.cacheL1Proc1Chip1.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout_3.addWidget(self.cacheL1Proc1Chip1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.cacheL2Chip1 = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacheL2Chip1.sizePolicy().hasHeightForWidth())
        self.cacheL2Chip1.setSizePolicy(sizePolicy)
        self.cacheL2Chip1.setMinimumSize(QtCore.QSize(322, 150))
        self.cacheL2Chip1.setMaximumSize(QtCore.QSize(322, 150))
        self.cacheL2Chip1.setBaseSize(QtCore.QSize(800, 300))
        self.cacheL2Chip1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL2Chip1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cacheL2Chip1.setObjectName("cacheL2Chip1")
        self.cacheL2Chip1.setColumnCount(6)
        self.cacheL2Chip1.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheL2Chip1.setItem(1, 5, item)
        self.cacheL2Chip1.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout_3.addWidget(self.cacheL2Chip1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.log = QtWidgets.QTextEdit(self.centralwidget)
        self.log.setObjectName("log")
        self.verticalLayout_5.addWidget(self.log)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Koherence"))
        self.label_4.setText(_translate("MainWindow", "Chip: 0"))
        self.label.setText(_translate("MainWindow", "Proc: 0 - L1"))
        item = self.cacheL1Proc0Chip0.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.cacheL1Proc0Chip0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "V"))
        item = self.cacheL1Proc0Chip0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.cacheL1Proc0Chip0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "S"))
        item = self.cacheL1Proc0Chip0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "O"))
        item = self.cacheL1Proc0Chip0.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tag"))
        item = self.cacheL1Proc0Chip0.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.cacheL1Proc0Chip0.isSortingEnabled()
        self.cacheL1Proc0Chip0.setSortingEnabled(False)
        item = self.cacheL1Proc0Chip0.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(1, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(1, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip0.item(1, 5)
        item.setText(_translate("MainWindow", "0"))
        self.cacheL1Proc0Chip0.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Proc: 1 - L1"))
        item = self.cacheL1Proc1Chip0.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.cacheL1Proc1Chip0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "V"))
        item = self.cacheL1Proc1Chip0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.cacheL1Proc1Chip0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "S"))
        item = self.cacheL1Proc1Chip0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "O"))
        item = self.cacheL1Proc1Chip0.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tag"))
        item = self.cacheL1Proc1Chip0.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.cacheL1Proc1Chip0.isSortingEnabled()
        self.cacheL1Proc1Chip0.setSortingEnabled(False)
        item = self.cacheL1Proc1Chip0.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(1, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(1, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip0.item(1, 5)
        item.setText(_translate("MainWindow", "0"))
        self.cacheL1Proc1Chip0.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Chip: 0 - L2"))
        item = self.cacheL2Chip0.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.cacheL2Chip0.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.cacheL2Chip0.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.cacheL2Chip0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "V"))
        item = self.cacheL2Chip0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.cacheL2Chip0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "S"))
        item = self.cacheL2Chip0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "O"))
        item = self.cacheL2Chip0.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tag"))
        item = self.cacheL2Chip0.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.cacheL2Chip0.isSortingEnabled()
        self.cacheL2Chip0.setSortingEnabled(False)
        item = self.cacheL2Chip0.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(1, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(1, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip0.item(1, 5)
        item.setText(_translate("MainWindow", "0"))
        self.cacheL2Chip0.setSortingEnabled(__sortingEnabled)
        self.label_10.setText(_translate("MainWindow", "Shared Memory"))
        item = self.sharedMemory.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.sharedMemory.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.sharedMemory.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.sharedMemory.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.sharedMemory.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.sharedMemory.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.sharedMemory.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.sharedMemory.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.sharedMemory.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.sharedMemory.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "10"))
        item = self.sharedMemory.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "11"))
        item = self.sharedMemory.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "12"))
        item = self.sharedMemory.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "13"))
        item = self.sharedMemory.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "14"))
        item = self.sharedMemory.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "15"))
        item = self.sharedMemory.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Position"))
        item = self.sharedMemory.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.sharedMemory.isSortingEnabled()
        self.sharedMemory.setSortingEnabled(False)
        item = self.sharedMemory.item(0, 0)
        item.setText(_translate("MainWindow", "0000"))
        item = self.sharedMemory.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(1, 0)
        item.setText(_translate("MainWindow", "0001"))
        item = self.sharedMemory.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(2, 0)
        item.setText(_translate("MainWindow", "0010"))
        item = self.sharedMemory.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(3, 0)
        item.setText(_translate("MainWindow", "0011"))
        item = self.sharedMemory.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(4, 0)
        item.setText(_translate("MainWindow", "0100"))
        item = self.sharedMemory.item(4, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(5, 0)
        item.setText(_translate("MainWindow", "0101"))
        item = self.sharedMemory.item(5, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(6, 0)
        item.setText(_translate("MainWindow", "0110"))
        item = self.sharedMemory.item(6, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(7, 0)
        item.setText(_translate("MainWindow", "0111"))
        item = self.sharedMemory.item(7, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(8, 0)
        item.setText(_translate("MainWindow", "1000"))
        item = self.sharedMemory.item(8, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(9, 0)
        item.setText(_translate("MainWindow", "1001"))
        item = self.sharedMemory.item(9, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(10, 0)
        item.setText(_translate("MainWindow", "1010"))
        item = self.sharedMemory.item(10, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(11, 0)
        item.setText(_translate("MainWindow", "1011"))
        item = self.sharedMemory.item(11, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(12, 0)
        item.setText(_translate("MainWindow", "1100"))
        item = self.sharedMemory.item(12, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(13, 0)
        item.setText(_translate("MainWindow", "1101"))
        item = self.sharedMemory.item(13, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(14, 0)
        item.setText(_translate("MainWindow", "1110"))
        item = self.sharedMemory.item(14, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sharedMemory.item(15, 0)
        item.setText(_translate("MainWindow", "1111"))
        item = self.sharedMemory.item(15, 1)
        item.setText(_translate("MainWindow", "0"))
        self.sharedMemory.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "Chip: 1"))
        self.label_6.setText(_translate("MainWindow", "Proc: 0 - L1"))
        item = self.cacheL1Proc0Chip1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.cacheL1Proc0Chip1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "V"))
        item = self.cacheL1Proc0Chip1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.cacheL1Proc0Chip1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "S"))
        item = self.cacheL1Proc0Chip1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "O"))
        item = self.cacheL1Proc0Chip1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tag"))
        item = self.cacheL1Proc0Chip1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.cacheL1Proc0Chip1.isSortingEnabled()
        self.cacheL1Proc0Chip1.setSortingEnabled(False)
        item = self.cacheL1Proc0Chip1.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(1, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(1, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc0Chip1.item(1, 5)
        item.setText(_translate("MainWindow", "0"))
        self.cacheL1Proc0Chip1.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("MainWindow", "Proc: 1 - L1"))
        item = self.cacheL1Proc1Chip1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.cacheL1Proc1Chip1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "V"))
        item = self.cacheL1Proc1Chip1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.cacheL1Proc1Chip1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "S"))
        item = self.cacheL1Proc1Chip1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "O"))
        item = self.cacheL1Proc1Chip1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tag"))
        item = self.cacheL1Proc1Chip1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.cacheL1Proc1Chip1.isSortingEnabled()
        self.cacheL1Proc1Chip1.setSortingEnabled(False)
        item = self.cacheL1Proc1Chip1.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(1, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(1, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL1Proc1Chip1.item(1, 5)
        item.setText(_translate("MainWindow", "0"))
        self.cacheL1Proc1Chip1.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("MainWindow", "Chip: 0 - L2"))
        item = self.cacheL2Chip1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.cacheL2Chip1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.cacheL2Chip1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.cacheL2Chip1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "V"))
        item = self.cacheL2Chip1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.cacheL2Chip1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "S"))
        item = self.cacheL2Chip1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "O"))
        item = self.cacheL2Chip1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tag"))
        item = self.cacheL2Chip1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data"))
        __sortingEnabled = self.cacheL2Chip1.isSortingEnabled()
        self.cacheL2Chip1.setSortingEnabled(False)
        item = self.cacheL2Chip1.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(1, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(1, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.cacheL2Chip1.item(1, 5)
        item.setText(_translate("MainWindow", "0"))
        self.cacheL2Chip1.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow", "Log"))
